// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIe0xX9HNCUQGlvhvn3IzzmJvOEvzvSg',
    appId: '1:806997351293:web:58a0c6f80c1710c4158a14',
    messagingSenderId: '806997351293',
    projectId: 'dopamine-tracker-web',
    authDomain: 'dopamine-tracker-web.firebaseapp.com',
    storageBucket: 'dopamine-tracker-web.firebasestorage.app',
    measurementId: 'G-0QFR9JNMTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxC5P9qnFGCav5fCV0sNsXEjKhs8aivkk',
    appId: '1:806997351293:android:655afb1c6db9295c158a14',
    messagingSenderId: '806997351293',
    projectId: 'dopamine-tracker-web',
    storageBucket: 'dopamine-tracker-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq2ppJgxAK6B-cu5NTaU8hpsQjrcy8xH0',
    appId: '1:806997351293:ios:9e1428e2dad0ab4a158a14',
    messagingSenderId: '806997351293',
    projectId: 'dopamine-tracker-web',
    storageBucket: 'dopamine-tracker-web.firebasestorage.app',
    iosBundleId: 'com.example.dopamineTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq2ppJgxAK6B-cu5NTaU8hpsQjrcy8xH0',
    appId: '1:806997351293:ios:9e1428e2dad0ab4a158a14',
    messagingSenderId: '806997351293',
    projectId: 'dopamine-tracker-web',
    storageBucket: 'dopamine-tracker-web.firebasestorage.app',
    iosBundleId: 'com.example.dopamineTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzIe0xX9HNCUQGlvhvn3IzzmJvOEvzvSg',
    appId: '1:806997351293:web:65d0a73d01c05c7e158a14',
    messagingSenderId: '806997351293',
    projectId: 'dopamine-tracker-web',
    authDomain: 'dopamine-tracker-web.firebaseapp.com',
    storageBucket: 'dopamine-tracker-web.firebasestorage.app',
    measurementId: 'G-SZ02XD9S64',
  );

}